### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by JimmyBassy** [clugg/csgo-autoaccept#2]
Is this injecting into the game? If is external does it edit memory of the game, I mean does it read write memory? And if so can this lead onto a ban?
Thank you and keep on the good work =)

**Comment by clugg** [comment]
It doesn't inject into the game nor read it's memory in any way, shape or form. It uses Pillow to grab captures of your screen on an interval, detects the accept button based on a set of potential RGBA values and clicks it. I cannot see any way this could possibly lead to a ban and I used it for a long time without any issues, but as with everything there are no guarantees - for example, Valve might start detecting mouse skips in the future (since the movement from current position to accept button is not interpolated over time).
Let me know if you have any other questions :)

**Comment by JimmyBassy** [comment]
Okay thank you for the clarification that was all!!
